services:
  mongo:
    image: mongo:6
    container_name: uzbek-mongo
    ports:
      - "27021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: M3nCh494741Kh4n!
      MONGO_INITDB_DATABASE: uzbek
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
