### GET /words
GET http://localhost:3421/words

### GET /words/:id
GET http://localhost:3421/words/c0f4cd99-2a3b-46e2-991e-55010c5b17b8

### POST /words
POST http://localhost:3421/words
Content-Type: application/json

{
  "word": "Xayr",
  "translation": "goodbye",
  "language": "uzbek",
  "partOfSpeech": "interjection"
}

### PATCH /words/:id
PATCH http://localhost:3421/words/c0f4cd99-2a3b-46e2-991e-55010c5b17b8
Content-Type: application/json

{
  "language": "uzbek"
}

### PUT /words/:id
PUT http://localhost:3421/words/c0f4cd99-2a3b-46e2-991e-55010c5b17b8
Content-Type: application/json

{
  "word": "Salom",
  "translation": "Hello",
  "partOfSpeech": "noun",
  "language": "uzbek"
}